src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class Booking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Ad::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="La date d'arrivé doit etre au bon format")
     * @Assert\GreaterThan("today", message="la date de reservation doit etre   supérieur à la date d'aujourd'hui", groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * 
     * @Assert\Date(message="La date de départ doit etre au bon format")
     * @Assert\GreaterThan(propertyPath="startDate", message="la date de départ doit etre plus éloigné que la date d'arrivé")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     * 
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * CallBack appelé à chaque fois que l'on veut persisté 
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function prePersist(){
        if(empty($this->createdAt)){
            $this->createdAt = new \DateTime();
        }

        if(empty($this->amount)){
            //iic on calcule le montant on fonction du prix de l'annonce et de la durée du séjour
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }


    /**
     * Cette fonction nous permet de savoir
     */
    public function isBookableDates(){
        //il faut connaitre les dates qui sont impossibles pour l'annonce 
        $notAvailableDays = $this->ad->getNotAvailableDays();
        //Il faut comparer les dates choisies avec les dates impossibles
        $bookingsDay = $this->getDays();

        $formatDay = function($day){
            return $day->format('Y-m-d');
        };
        //Convertit les jours de réservation bookingsDay de type DateTime en des chaines de caractère que l'on peut facilement comparer
        $days = array_map($formatDay,$bookingsDay);

        //Un tableau des journées non disponible en chaine de caractère
        $notAvailable = array_map($formatDay, $notAvailableDays);

        //Ici on compare si les jours de réservation sont égales aux jours non disponibles
        foreach($days as $day){
            if(array_search($day, $notAvailable) !== false) return false;
        }

        return true;

    }

    /**
     * Permet de récupéré un tableau de journée qui correspondent à ma reservation
     * 
     * @return array un tableau d'objet datetime qui représente le jour des réservations
     */
    public function getDays(){
        $resulats = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );

        $days = array_map(function($daysTimestamp){
            return new DateTime(date('Y-m-d', $daysTimestamp));
        }, $resulats);

        return $days;
    }

    //Cette fonction nous permet de récupéré le nombre de jour entre la date de départ et la date d'arrivé

    public function getDuration(){
        //ici on fais la différence entre la date de départ et la date d'arrivé
        $diff = $this->endDate->diff($this->startDate);

        //Ici on récupère uniquement le nombre de jour 
        return $diff->days;
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

   
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\DataTransformers\FrenchToDateTimeTransformer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class BookingType extends ApplicationType
{
    
    public function __construct(FrenchToDateTimeTransformer $transformer)
    {
        $this->transformer = $transformer;
    }
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate',TextType::class, $this->getConfiguration('La date d\'arrivé','la date à l\'aquelle vous compter arriver'))
            ->add('endDate',TextType::class, $this->getConfiguration('La date de départ','la date à l\'aquelle vous compter quittez les lieux'))
            ->add('comment', TextareaType::class, $this->getConfiguration(false, 'Si vous avez un commentaire n\'hésitez pas à le mettre',['required'=> false]))
            ;
        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
            'validation_groups' => [
                "Default", "front"
            ]
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class BookingController extends AbstractController
{
    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }
    /**
     * permet de faire une réservation
     * @Route("/ads/{slug}/booking", name="booking_create")
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad, Request $request)
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking, [
            "validation_groups" => ['default', 'front']
        ]);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $booking->setBooker($this->getUser())
                    ->setAd($ad)
                    ;

            //Si les dates ne sont pas disponible

            $this->em->persist($booking);
            if(!$booking->isBookableDates()){
                $this->addFlash('warning','Les dates que vous avez choisie sont déja prise');
            }else{
                $this->em->flush();

                return $this->redirectToRoute('booking_show', ['id' => $booking->getId(), 'success'=> true]);
            }
            
            
        }

        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }
    /**
     * permet d'afficher la page d'une réservation
     * @Route("/booking/{id}", name="booking_show")
     * @param Booking $booking
     * @return Response
     */
    public function show(Booking $booking, Request $request){
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $comment->setAd($booking->getAd())
                    ->setAuthor($this->getUser())
            ;

            $this->em->persist($comment);
            $this->em->flush();

            $this->addFlash('success','Votre commentaire à bien été pris en compte');
        }

        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form' => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BookingController!{% endblock %}

{% block stylesheets %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" />
  <style>
    .datepicker table tr td.disabled, .datepicker table tr td.disabled:hover{
        color: firebrick;
        
    }
  </style>
{% endblock %}
{% block body %}
    <div class="container">
        <h1>Reservez l'annonce : {{ad.title}}</h1>
        <p>Vous etes sur le point de reservez l'annonce <strong>{{ad.author.fullname}}</strong></p>
        {{form_start(form)}}
            <h4>Commencez par nous dire les dates à laquelle vous souhaitez</h4>
            <div class="row">
                <div class="col">
                    {{form_row(form.startDate)}}
                </div>
                <div class="col">
                    {{form_row(form.endDate)}}
                </div>
            </div>
            <h4>Montant du séjour : <span id="amount">...</span></h4>
            <span id="days">0 nuit(s)</span> à {{ad.price}} / nuit

            <h4>Avez-vous un commentaire? Faites nous en part</h4>
            {{form_row(form.comment)}}
            <p>Est-ce pour un voyage? Des vacances? Avec nous vous aurez le logement qu'il vous faut</p>
        <button type="submit" class="btn btn-success">Je resèrve</button>
        {{form_end(form)}}
        
    </div>
{% endblock %}

{% block javascripts %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous"></script>
    <script type="application/javascript">
        $(document).ready(function(){
            $('#booking_startDate, #booking_endDate').datepicker({
                format: 'dd/mm/yyyy',
                datesDisabled: [
                    {% for day in ad.notAvailableDays %}
                        "{{day.format('d/m/Y')}}",
                    {% endfor %}
                ],
                startDate: new Date()
            });
            $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
        });

        function calculateAmount(){
            const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

            //(\d+)\/(\d+)\/(\d{4})
            const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

            if(startDate && endDate && startDate < endDate){
                const dayTime = 24 * 60 * 60 * 1000;
                const interval = endDate.getTime() - startDate.getTime();

                const days = interval / dayTime;

                const amount = days * {{ad.price}};

                $('#days').text(days);
                $('#amount').text(amount.toLocaleString('fr-FR'));

                console.log(amount);
            }
        }
    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends "base.html.twig" %}

{% block body %}
{% set ad = booking.ad %}
{% set author = booking.ad.author %}

    
    <div class="container">
        <h1>Vorte reservation n {{booking.id}}</h1>
        {% if app.request.query.get('success') %}
            <div class="alert alert-success">
                <h4>Votre réservation à bien été pris en compte</h4> 
            </div>
        {% endif %}
        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Détails</h2>
                    <dl class="row">
                        <dl class="col-md-4">Numéro</dl>
                        <dt class="col-md-8">{{booking.id}}</dt>
                        <dl class="col-md-4">Date d'arrivée</dl>
                        <dt class="col-md-8">{{booking.startDate | date('d-m-Y')}}</dt>
                        <dl class="col-md-4">Date de départ</dl>
                        <dt class="col-md-8">{{booking.endDate | date('d-m-Y')}}</dt>
                        <dl class="col-md-4">Nombre de nuit</dl>
                        <dt class="col-md-8">{{booking.duration}}</dt>
                        <dl class="col-md-4">Montant Total</dl>
                        <dt class="col-md-8">{{booking.amount}}</dt>
                        <dl class="col-md-4">Commentaire</dl>
                        <dt class="col-md-8">{{booking.comment | default("Aucun commentaire")}}</dt>
                    </dl>
                    <hr>

                    <h2 class="alert-heading">Votre hote</h2>

                    <div class="row">
                        <div class="col-3">
                            <img src="{{author.picture}}" class="avatar avatar-medium" alt="Avatar de {{author.fullname}}">
                        </div>
                        <div class="col-9">
                            <h4><a href="{{path('user_show',{slug: author.slug})}}">{{author.fullname}}</a></h4>

                            <span class="badge badge-primary">{{author.ads | length}} Annonces</span>
                        </div>
                    </div>
                    {{author.description}}
                    <a href="{{path('user_show',{slug: author.slug})}}" class="btn btn-primary">Plus d'info sur {{author.firstname}}</a>
                </div>
                <div class="alert alert-light" id="comment">
                    <h2 class="alert-heading">Votre avis compte?</h2>
                    {% if date() > date(booking.endDate) %}
                        {% set comment = booking.ad.commentFromAuthor(app.user) %}
                        {% if comment is not null %}
                            <blockquote>{{comment.content}}</blockquote>
                            Note: <strong>{% include "shared/_rating.html.twig" with {'rating': comment.rating} %}</strong>
                        {% else %}
                             {{form_start(form)}}
                                {{form_widget(form)}}
                                <button type="submit" class="btn btn-success">Notez</button>
                            {{form_end(form)}}
                        {% endif %}
                    {% else %}
                        <p>Vous ne pouvez pas encore noté votre voyage car vous avez pas encore terminé votre séjour</p>
                    {% endif %}
                </div>
            </div>
            
            <div class="col">
                <h2>Votre hébergement</h2>
                <h4>
                    <a href="{{path('ad_show', {slug: ad.slug})}}">{{ad.title}}</a>
                </h4>
                <img src="{{ad.coverImage}}" alt="" class="img-fluid">
                {{ad.contenu | raw}}

                <a href="{{path('ad_show',{slug: ad.slug})}}" class="btn btn-primary">Plus d'infos sur l'annonce</a>
            </div>
        </div>
    </div>
{% endblock %}