src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Repository\AdRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use DateTime;
use PhpParser\Node\Expr\Cast\Array_;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=AdRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"title"},
 *  message="Une autre annonce possède déjà ce titre"
 * )
 */

class Ad
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *  min=5, 
     *  max=255, 
     *  minMessage="Le titre avoir minimun 10 caractère",
     *  maxMessage="Le titre ne doit pas dépasser les 10 caractères"
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $introduction;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="Ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="ad", orphanRemoval=true)
     */
    private $comments;



    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'obtenir la note globale d'une annonce
     */
    public function getAvgRating(){
        //Calculer la somme des notation
        $somme = array_reduce($this->comments->toArray(), function($totale, $comment){
            return $totale + $comment->getRating();
        },0);

        if(count($this->comments) > 0) return $somme / count($this->comments);

        return 0;

    }

    /**
     * permet d'initilaiser notre slug
     * 
     * permet de dire à notre manager de toujours éxécuter cette fonction
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function initializeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }
    /**
     * Permet d'obtenir un tableau les jours qui ne sont disponibles pour une annonce
     * 
     * @return Array un tabkeau d'objet DateTime
     */
    public function getNotAvailableDays(){
        $notAvailablesDays = [];

        foreach($this->bookings as $booking){
                //Calculer les jours qui se trouve entre la date de départ et d'arrivée
                $resulat = range(
                    $booking->getStartDate()->getTimestamp(),
                    $booking->getEndDate()->getTimestamp(),
                    24 * 60 * 60
            );

            //Ici on convertit le resultat de timestamp en veritable datetime
            $days = array_map(function($dayTimestamp){
                return new DateTime(date('Y-m-d',$dayTimestamp));
            }, $resulat);

            //On ajoute le jour non disponible dans le tableau des jours non disponible
            $notAvailablesDays = array_merge($notAvailablesDays, $days);
        }

        return $notAvailablesDays;
    }

    /**
     * Cette fonction nous permet de récuépérer le commentaire d'un auteur par rapport à une annonce
     */
    public function getCommentFromAuthor(User $author){
        foreach($this->comments as $comment){
            if($comment->getAuthor() == $author){
                return $comment;
            }
        }

        return null;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;
 
        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }

   
}

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use App\Form\ImageType;
use App\Form\ApplicationType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdType extends ApplicationType
{
   
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, $this->getConfiguration('Titre', 'Entrer un super titre pour votre annonce'))
            ->add('slug',TextType::class, $this->getConfiguration('Slug','Adresse web (automatique)', [
                'required' => false
            ]))
            ->add('coverImage',UrlType::class, $this->getConfiguration('Url de l\'image principale', 'Entrer url de votre image'))
            ->add('introduction', TextType::class, $this->getConfiguration('Introduction', 'Donnez une introduction à votre annoce'))
            ->add('contenu', TextareaType::class, $this->getConfiguration('Description détaillé', 'Tapez une description qui donne vraiment envie de venir chez vous'))
            ->add('rooms', IntegerType::class, $this->getConfiguration('Nombre de chambre', 'Entrer le nombre de chambre de votre maison'))
            ->add('price',MoneyType::class, $this->getConfiguration('Prix par nuit', 'Entrer le prix par nuit de vos chambres'))
            ->add('images',CollectionType::class, [
                'entry_type' => ImageType::class,
                'allow_add' => true,
                'allow_delete' => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ad::class,
        ]);
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Image;
use App\Form\AdType;
use App\Repository\AdRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class AdController extends AbstractController
{
    public function __construct(AdRepository $adRepository, EntityManagerInterface $em)
    {
         $this->adRepository = $adRepository;
         $this->em = $em;
    }
    /**
     * page d'affichage des annonces
     * @Route("/ads", name="ads_index")
     * @return Response
     */
    public function index()
    {

        //$repo = $this->getDoctrine()->getRepository(Ad::class);
        $ads = $this->adRepository->findAll();
        return $this->render('ad/index.html.twig', [
            'ads' => $ads
        ]);
    }
    /**
     * Permettra de créer une annonce
     * @Route("/ads/create", name="ad_create")
     * @IsGranted("ROLE_USER")
     * @param Request
     * @return Response
     */
    public function create(Request $request){
        $ad = new Ad();
       
        $form = $this->createForm(AdType::class, $ad);
        $form->handleRequest($request);
       
        if($form->isSubmitted() && $form->isValid()){
            $this->em->persist($ad);
            foreach($ad->getImages() as $images){
                //ici on gére notre collection d'image on récupère chaque image et on là  lie à l'annonce qui correspond avant de la persister
                $images->setAd($ad);
                $this->em->persist($images);
            }

            $ad->setAuthor($this->getUser());
            $this->em->flush();

            $this->addFlash('success', 'l\'annonce '.$ad->getTitle().' que vous avez créé à bien été enregistré');
            return $this->redirectToRoute('ad_show',[
                'slug' => $ad->getSlug()
            ]);
        }
        return $this->render('ad/create.html.twig',[
            'form' => $form->createView()
        ]);
    }

   /**
     * cette fonction permettra d'afficher une seule annonce
     * @param Ad $ad
     * @Route("/ads/{slug}", name="ad_show")
     * @return Response
     */

     //ici nous faisons une injection de dépendance alors symfony prendra notre slug et 
     //va trouver l'annonce qui correspond à notre slug ainsi il nous retournera directment l'annonce en question il s'agit la du param converter
    public function show(Ad $ad){
        return $this->render('ad/show.html.twig',[
            'ad' => $ad
        ]);
    }
    /**
     * permet d'afficher le formulaire d'édition
     * @Route("/ads/{slug}/edit", name="ad_edit")
     * @Security("(is_granted('ROLE_USER') and user === ad.getAuthor()) or is_granted('ROLE_ADMIN')", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier")
     * 
     * @param Ad $ad
     * @param Request $request
     * @return Response
     */
    public function edit(Ad $ad,Request $request){
        $form = $this->createForm(AdType::class, $ad);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $this->em->persist($ad);
            foreach($ad->getImages() as $images){
                //ici on gére notre collection d'image on récupère chaque image et on là  lie à l'annonce qui correspond avant de la persister
                $images->setAd($ad);
                
                $this->em->persist($images);
            }
            $this->em->flush();
            $this->addFlash('warning', 'l\'annonce '.$ad->getTitle().'  à bien été modifier');
            return $this->redirectToRoute('ad_show',[
                'slug' => $ad->getSlug()
            ]);
        }
        return $this->render('ad/edit.html.twig',[
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet de supprimer une annonce
     * @Route("/ads/{slug}/delete", name="ad_delete")
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Vous n'avez pas le droit de supprimer cette annonce")
     * @param Ad $ad
     * @return Response
     */
    public function delete(Ad $ad):Response
    {
        $this->em->remove($ad);
        $this->em->flush();
        $this->addFlash("success", "L\'annonce ".$ad->getTitle()." a bien été supprimé ");
        return $this->redirectToRoute('ads_index');
    }
}

templates/ad/_ad.html.twig
{% set url = path('ad_show', {slug: ad.slug})%}
    <div class="col-md-4">
            <div class="card mb-3">
                <div class="card-header">
                Appartement {{ad.rooms}} pièces <strong>{{ad.price}} &euro; / nuit</strong> <br>
                {% if ad.comments | length > 0 %}
                    {% include "shared/_rating.html.twig" with {'rating': ad.avgRating} %}
                {% else %}
                    <small>Pas encore noté</small>
                {% endif %}
                
                </div>
                <a href="{{url}}">
                <img src="{{ad.coverImage}}" alt="Une image normale" style="height: 200px; width: 100%; display: block">
                </a>
            <div class="card-body mb-3">
            <a href="{{url}}">
                <p class="card-title">{{ad.title}}</p>
            </a>
            <p class="card-text">{{ad.introduction}}</p>
            <a href="{{url}}" class="btn btn-secondary">Voir l'annonce</a>
            {% if app.user and app.user == ad.author %}
                <a href="{{path('ad_edit', {slug: ad.slug})}}" class="btn btn-secondary">Modifier l'annonce !</a>
                
            {% endif %}
        </div>
    </div>
</div>

templates/ad/_collection.html.twig
{#Ici nous definissons l'affiche de notre formulaires add_images grace à la convention _nom_widget qui nous permet de modifier l'affichage d'un champs particulier
Le widget correspond au texte sans label
La row correspond à toute le champs widget inclu
#}
{% block _ad_images_widget %}
    <p>Ajouter vos images supplémentaire ici</p>
    {{form_widget(form)}}
    {#ici nous definissons un champs caché qui représente le nombre de nos sous formulaire#}
    <input type="hidden" id="widgets-counter" value="0">
    <button type="button" id="add-image" class="btn btn-danger">Ajouter une image</button>
{% endblock %}

{#Ici nous définissons comment une ligne va s'afficher c'est à dire label et widget
dans notre cas nous voulons juste afficher sur une ligne le widget
#}

{% block _ad_images_entry_row %}
    {{form_widget(form)}}
{% endblock %}

{#Ici nous definissons l'affiche des champs de notre formualire qui represente des entrées grace à l'attribut entry_type qui se trouve dans notre entité adType

#}

{% block _ad_images_entry_widget %}
    {#Ici nous ajoutons id dynamiquement pour pouvoir faire la suppression de l'entrée correspondantes#}
    <div class="form-group" id="block_{{id}}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{form_widget(form.url)}}
                        {{form_errors(form.url)}}
                    </div>
                    <div class="col">
                        {{form_widget(form.caption)}}

                        {#Nous permet de capter nos erreur et de les afficher#}
                        {{form_errors(form.caption)}}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">X</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/ad/create.html.twig
{% extends "base.html.twig" %}
{% block title %}RBNB crée ton annonce{% endblock %}

{#ici nous disons à twig de prendre en compte la personnalisation de notre affichage pour le champs ad_images qui est notre sous formulaire d'images#}
{% form_theme form 'ad/_collection.html.twig' %}
{% block body %}
    <div class="container">
        <h1>Crée ton annonce</h1>
        <div>
            {{form_start(form)}}
                {{form_widget(form)}}
                <button class="btn btn-danger">Enregistrer l'annonce</button>
            {{form_end(form)}}
        </div>
    </div>
{% endblock %}


{% block javascripts %}
    <script>
        $('#add-image').click(function(){
            //je récupère la valeur de mon champs caché widgets-counter
            const numberOfEntry = +$('#widgets-counter').val();
            console.log(numberOfEntry);

            //maintenant je récupère le prototype d'une nouvelle entrée de mon formulaire ad_images et je l'atribut name par le numéro de l'entrée récupéré ci-dessus
            const templat = $('#ad_images').data('prototype').replace(/__name__/g, numberOfEntry);
            //j'injecte simplement le code de mon prototype dans ma div pour créer le champs au clic du button

            $('#ad_images').append(templat);
            $('#widgets-counter').val(numberOfEntry + 1);
            handleDelete();
        });
        
        //je crée la function qui permettra de gérer la suppression d'une entrée

        function handleDelete(){
            //dataset représente tous les 
            $('button[data-action="delete"]').click(function(){
                const target = this.dataset.target;
                $(target).remove();
            });
        }
        handleDelete();
    </script>
{% endblock %}

templates/ad/edit.html.twig
{% extends "base.html.twig" %}
{% block title %}Modifier votre annonce{% endblock %}
{% form_theme form 'ad/_collection.html.twig' %}
{% block body %}
    <div class="container">
        <h1>Modifier l'annonce {{ad.title}} ton annonce</h1>
        <div>
            {{form_start(form)}}
                {{form_widget(form)}}
                <button class="btn btn-danger">Modifier l'annonce</button>
            {{form_end(form)}}
        </div>
    </div>
{% endblock %}


{% block javascripts %}
    <script>
        $('#add-image').click(function(){
            //je récupère la valeur de mon champs caché widgets-counter
            const numberOfEntry = +$('#widgets-counter').val();
            console.log(numberOfEntry);

            //maintenant je récupère le prototype d'une nouvelle entrée de mon formulaire ad_images et je l'atribut name par le numéro de l'entrée récupéré ci-dessus
            const templat = $('#ad_images').data('prototype').replace(/__name__/g, numberOfEntry);
            //j'injecte simplement le code de mon prototype dans ma div pour créer le champs au clic du button

            $('#ad_images').append(templat);
            $('#widgets-counter').val(numberOfEntry + 1);
            handleDelete();
        });
        
        //je crée la function qui permettra de gérer la suppression d'une entrée

        function handleDelete(){
            //dataset représente tous les 
            $('button[data-action="delete"]').click(function(){
                const target = this.dataset.target;
                $(target).remove();
            });
        }
        handleDelete();

        //je crée la function qui récupère le nombre de mes champs images

        function updateCounter(){
            const count = $('#ad_images div.form-group').length;
            $('#widgets-counter').val(count);
        }
        updateCounter();
    </script>
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}RBNB ! Nos annonces{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="display-4 my-3">Voici toutes nos annonces </h1>
        <div class="row">
            {% for ad in ads %}
                {% include "ad/_ad.html.twig" %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}RBNB ! Nos annonces{% endblock %}

{% block body %}

        <div class="prince text-white" style="background-image: url({{ad.coverImage}})">
            <div class="container">
                <h1>{{ad.title}}</h1>

                <p>{{ad.introduction}}</p>
                <p class="h2"> <strong>{{ad.rooms}} chambres</strong>  <strong>{{ad.price}} &euro;</strong></p>
                <a href="{{path('booking_create', {slug: ad.slug})}}" class="btn btn-primary">Reservez !</a>
                {% if (app.user and app.user == ad.author) or is_granted('ROLE_ADMIN') %}
                    <a href="{{path('ad_edit', {slug: ad.slug})}}" class="btn btn-secondary">Modifier l'annonce !</a>
                    <a href="{{path('ad_delete', {slug: ad.slug})}}" class="btn btn-danger" onclick="confirm('Voulez-vous vraiment supprimer l\'annonce {{ad.title}}?')">Supprimer l'annonce !</a>
                {% endif %}
            </div>
        </div>
        
    <div class="container mt-3" >
        
        <div class="row">
            <div class="col-md-8 mb-3 test">
                {{ad.contenu}}

                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for image in ad.images %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{loop.index0}}" {% if loop.first %}class="active"{% endif %}
                        ></li>
                    {% endfor %}
                    
                </ol>
                <div class="carousel-inner">
                    {% for image in ad.images %}
                        <div class="carousel-item {% if loop.first %}active{%endif%}">
                        <img src="{{image.url}}" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>{{ad.title}}</h5>
                            <p>{{image.caption}}</p>
                        </div>
                        </div>
                    {% endfor %}
                    
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
                </div>
                <hr>

                {% if (ad.comments | length) > 0 %}
                    <h2 class="h2">Commentaire de nos voyageurs</h2>
                    
                    
                    <div class="alert alert-info">
                        <h4 class="alert-heading text-center">
                            <div class="row align-items-center">
                                <div class="col">
                                    Note Globale donnée par nos voyageurs
                                    
                                </div>
                                <div class="col">
                                    {% include "shared/_rating.html.twig" with {'rating': ad.AvgRating} %}<br>
                                    <small>(Calculé sur {{ad.comments | length}} avis)</small>
                                </div>
                            </div>
                        </h4>
                    </div>
                    {% for comment in ad.comments %}
                        <div class="bg-light rounded mt-2 py-3 px-3">
                            <strong>{{comment.author.fullname}}</strong> a dit:
                            <blockquote>
                                {{comment.content}}
                            </blockquote>
                            <strong>Note donnée: 
                            {% include "shared/_rating.html.twig" with {'rating': comment.rating} %}
                            </strong>
                        </div>
                    {% endfor %}

                {% else %}
                    
                <h2>L'annonce n'a pas encore de commentaire</h2>
                {% endif %}
            </div>
            <div class="col">
            {% set a = ad.author%}
                <div class="row">
                    <div class="col-md-4">
                        <a href="{{path("user_show",{slug: a.slug})}}">
                            <img src="{{a.picture}}" alt="avatar de {{a.fullname}}">
                        </a>
                    </div>
                    <div class="col mx-2">
                        <a href="{{path("user_show",{slug: a.slug})}}">
                            <h3>{{a.fullname}}</h3>
                        </a>
                        <span class="badge badge-primary">{{a.ads | length}} annonces</span>
                    </div>
                    <div class="col">
                        <p>{{a.intro}}</p>
                        <br>
                        <p>{{a.description}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}